version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: | 
            sudo npm install
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: grunt build
          command: |
            sudo npm install -g grunt-cli
            sudo grunt build
            ls -la
      - run:
          name: update cv
          command: |
            mkdir cv
            cd cv
            git clone https://github.com/turgayh/blog.git
            cd blog
            rm -rf content/resume/*
            cp -r ../../dist/* ./content/resume
      - run:
          name: push blog Github Repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then  
              git config --global user.email "turgayh@itu.edu.tr"
              git config --global user.name "turgayh"
              cd ./cv/blog
              git add .
              git commit -m "Circle CI Update Website | Build Number:${CIRCLE_BUILD_NUM}"
              git push -q https://${DEPLOY_KEY}@github.com/turgayh/blog master
            fi
