version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: | 
            sudo npm install -g npm@5
            sudo npm install
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: grunt build
          command: |
            sudo npm install -g grunt-cli
            ls -la
            sudo grunt build
      - run:
          name: update cv
          command: |
            mkdir cv
            cd cv

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
